### ISSUE TITLE
Does not work when source is written in Jade

### ISSUE THREAD

**Issue by binarykitchen** [haydenbleasel/gulp-robots#1]
```js
gulp.task('html', ['clean:html'], function() {
    return gulp.src('src/views/base.jade')
        .pipe(plugins.jade())
        .pipe(plugins.robots({ out: 'robots.txt' }))
        ...
})
```

throws

```
.../node_modules/gulp-robots/index.js:29
                    throw error;
                          ^
Error: ENOENT: no such file or directory, open 'src/views/base.html'
    at Error (native)
    ---- async ----
```

**Comment by haydenbleasel** [comment]
I'm not sure I can write it to handle every single HTML pre-processing language, and the typical use case for robots.txt is only during a production build i.e. when your HTML is being compiled. Is there a reason it can't be in your production build process only?

**Comment by binarykitchen** [comment]
Understand but why do you have to access the HTML file when you can fetch the HTML content from the stream within gulp? In the above example, the jade plugin will compile it to HTML and after that, you can parse the HTML directly instead of accessing the raw HTML file.

**Comment by haydenbleasel** [comment]
Oh right, good point. Let me look into this.

**Comment by haydenbleasel** [comment]
Hey @binarykitchen, this should be solved as of now - the source is read from the stream rather than the original file.

**Comment by binarykitchen** [comment]
thanks, that's a good change!
