### ISSUE TITLE
Migrate

### ISSUE THREAD

**Issue by haydenbleasel** [haydenbleasel/gulp-robots#3]
@binarykitchen @ocubom @dankantor

Hey all,

I've done a large refactor on robots-generator and it now supports a "streaming" mode for Gulp. This means that `gulp-robots` will be deleted and `robots-generator` will take it's place. This will allow me to manage the module better and removes a pointless Gulp wrapper:

```js
var robots = require('robots-generator').stream;

gulp.task('default', function () {
    gulp.src('index.html')
        .pipe(robots({
            useragent: '*',
            allow: ['folder1/', 'folder2/'],
            disallow: ['cgi-bin/']
        }))
        .pipe(gulp.dest('robots.txt'));
});
```

Once I know you've all migrated, I'll close this issue. Also, if you could star [robots-generator](https://github.com/haydenbleasel/robots-generator) that'd be cool too haha :)

**Comment by binarykitchen** [comment]
thanks - works fine like that but you better want to add an undefined check when allow or disallow aren't specified at all.

**Comment by haydenbleasel** [comment]
Hey @binarykitchen, I don't know if that's an issue since it falls back to an empty array i.e.

```js
const options = _.defaults(params || {}, { allow: [] });
if (options.allow.length) {
    _.each(options.allow, (a) => configuration.push(`Allow: ${ a }`));
}
```

**Comment by haydenbleasel** [comment]
Also CC: @Lsong and @berstend for starring.

**Comment by haydenbleasel** [comment]
Also CC: @song940 and @berstend for starring.

**Comment by philkunz** [comment]
@haydenbleasel Since npm already throws the deprecated warning, it should be mentioned in the readme to save people the trouble of first installing gulp-robots before robots-generator...

That being said... wouldn't it make sense to simply hand through robots-generator to gulp-robots by simply doing a index.js for gulp-robots that says

```javascript
var gulpRobots = require('robots-generator').stream;
module.exports = gulpRobots;
```

 This would allow use of gulp-robots with tools like gulp-load-plugins that make life super easy, which rely on standard npm "gulp-" module naming, but wouldn't add any complexity or update struggles despite version pinning. You can make version pinning really easy through automated pr's for new versions of robots-generator with greenkeeper.io, so gulp-robots automatically follows robots-generator.

**Comment by binarykitchen** [comment]
@haydenbleasel it is logical. check the robots.txt standard. `/` is default for allow, so use that when the allow option is not specified. same goes for disallow whose default option is undefined i think.

btw, agree with all what @philkunz said

**Comment by dankantor** [comment]
@haydenbleasel just updated to 2.0. When I pass in 'sitemap', it doesn't come out in the robots.txt file. If I add it as `<link rel="sitemap" />` then it does. Other than that issue, it's working nicely.

**Comment by haydenbleasel** [comment]
@binarykitchen @philkunz Good point. I'll un-deprecate the module and store it as an orphan branch of the parent module. The idea behind this was with good intention, I was following [wiredep](https://github.com/taptapship/wiredep#gulpjs)'s example, but I can see now why it's useful to have a gulp wrapper. I'll get this sorted out.

**Comment by haydenbleasel** [comment]
Hey @dankantor, thanks for the heads up. Fixed in `robots-generator@2.3.3`

**Comment by haydenbleasel** [comment]
Hey all (@binarykitchen @philkunz @dankantor @ocubom), re-released this module as a tiny wrapper under https://github.com/haydenbleasel/robots-generator/tree/gulp. You can install and use the exact same way as `gulp-robots` is currently. Could you try it out for me if possible?

**Comment by dankantor** [comment]
@haydenbleasel nice! is it on NPM?

**Comment by haydenbleasel** [comment]
@dankantor Yep, just update `gulp-robots`.

**Comment by dankantor** [comment]
@haydenbleasel I upgraded to 2.0.2. Sitemap is now working correctly but it is now building in the wrong place. I have this `.pipe(gulp.dest('./build/robots.txt'));` and it is putting it in `build/robots.txt/robots.txt'`

**Comment by dankantor** [comment]
Ah you know what, ignore my last comment. I was doing it wrong. I had that as a work around before. It should really be `.pipe(gulp.dest('./build/'));` which works as expected.
